### ISSUE TITLE
Error recibir premio

### ISSUE THREAD

**Issue by Ruytaro** [Cadiducho/40ServidoresMC#14]
Da un error extraño al reclamar el premio con /vote40.
El error aparece de manera aleatoria, pero permanece bastante tiempo.
Un extracto de los logs:
[17:35:34] [Server thread/INFO]: Ruytaro issued server command: /VOTE40
[17:35:34] [Server thread/INFO]: [40ServidoresMC](Fundador) Ruytaro acaba de votarnos! usa /voto40 para reclamar tu premio.
[17:35:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'vote40' in plugin 40ServidoresMC v1.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) ~[craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at org.bukkit.craftbukkit.v1_7_R2.CraftServer.dispatchCommand(CraftServer.java:696) ~[craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.PlayerConnection.handleCommand(PlayerConnection.java:952) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:814) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.NetworkManager.a(NetworkManager.java:147) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:657) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:250) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:548) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:459) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618) [craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 11174677
        at com.cadiducho.cservidoresMC.util.Inventario.getKit(Inventario.java:27) ~[?:?]
        at com.cadiducho.cservidoresMC.util.Inventario.darPremio(Inventario.java:45) ~[?:?]
        at com.cadiducho.cservidoresMC.cmd.VoteCMD.onCommand(VoteCMD.java:43) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.7.5-R0.1-20140402.020013-12.jar:git-Bukkit-1.7.2-R0.3-11-g08fad7a-b3037jnks]
        ... 13 more

**Comment by Cadiducho** [comment]
Tienes mal configurada la config del premio FISICO, o la tienes activada y la lista de este vacio.... ¿puede ser eso? Compruebalo por favor

**Comment by Ruytaro** [comment]
Correcto, era el premio físico.Eliminé los valores, pero no sabia que hubiera que desactivarlo.Tardé a comentarlo por si era otra cosa, pero lleva sin fallar desde que lo actualizé.
¿Podrias indicar mas claramente en la wiki la configuracion? Sé que es basico, pero no vi que fuera ese el problema por ningun lado...
Muchas gracias por la pronta respuesta.

**Comment by Cadiducho** [comment]
Claro; intentaré dejar más clara la parte de configuración. Gracias por ayudar!
